[package]
name = "pxp-diagnostics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
pxp-span = { path = "../span" }
pxp-token = { path = "../token" }
