[package]
name = "pxp-lsp"
version = "0.1.0"
edition = "2021"
license-file.workspace = true
rust-version.workspace = true

[dependencies]
lsp-server = "0.7.6"
lsp-types = "0.97.0"
serde = "1.0.209"
serde_json = "1.0.127"
