[package]
name = "pxp-type"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
pxp-span = { path = "../span" }
serde = { version = "1.0.193", features = ["derive"] }
