[package]
name = "snappers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
pretty_assertions = "1.4.0"
